### ISSUE TITLE
Can `hash` support a secret parameter?

### ISSUE THREAD

**Issue by brettchalupa** [Rabbit-Company/Argon2id-WASM#3]
Thank you for building and maintaining this library, it's been helpful for getting password hashing and verifying working with Deno on Deno Deploy. I'm wondering if there's a way to specify a secret when hashing, with an API like this:

``` ts
hash("supersecure", { secret: Deno.env.get("SECRET_KEY_BASE") })
```

And then to verify:

``` ts
verify(passwordHash, "supersecure", Deno.env.get("SECRET_KEY_BASE"))
```

Adding one more aspect of protection to hashed data like passwords would be ideal.

[@felix2/argon supports this](https://jsr.io/@felix/argon2/doc/~/HashOptions), but unfortunately it relies upon FFI which doesn't work on Deno Deploy. [That library's verify docs.](https://jsr.io/@felix/argon2/doc/~/verify)

**Comment by zigazajc007** [comment]
Hello,

[@felix2/argon supports](https://jsr.io/@felix/argon2/doc/~/HashOptions) library seems to automatically combine secret key with data / password.

You can do the same by calling:
```js
const encodedHash = await Argon2id.hashEncoded("supersecure" + Deno.env.get("SECRET_KEY_BASE"));

// and to verify

const match = await Argon2id.verify(encodedHash, "supersecure" + Deno.env.get("SECRET_KEY_BASE"));
```
